eureka:
  client:
    register-with-eureka:true
    fetchRegistry:true
  serviceUrl:
    defaultZone:https://pos-discovery.herokuapp.com/eureka/
  instance:
    hostname:pos-discovery.herokuapp.com
application:
  name:POS-CUSTOMER